### ISSUE TITLE
Need for question type which includes both _choices_ and _textual_ feedback

### ISSUE THREAD

**Issue by minimalisti** [piehei/prplatform#2]
There is a need to be able to create questions that combine feedback types. The need to be able to include both _choices_ and _textual_ feedback has arisen in our use.

**Comment by piehei** [comment]
If I understand you correctly, you want to create a question that the student answers when the student is doing a peer-review of another student, and that question needs to include both choices and textual inputs from the student. Do I understand you correctly or do you mean something else?

If I got you, why cannot you use multiple questions with different types?

**Comment by minimalisti** [comment]
You understood the scenario correctly: student A peer-reviews a submission by student B, and the feedback given by A should have both _textual_ and _choices_ in it.

Your suggested solution using two questions in the feedback works well!I just wasn't able to use all the magnificent capabilities fo PRPlatform. :-)

I will close this issue.

**Comment by piehei** [comment]
Hahahahahahahahahhahaha, it's a burning pile of --.

Multiple questions are supported, yes, and you can even reorder them. Think about that!

Thanks for the issue anyhow and keep them coming. Any issues are worth reporting IMO. Especially those that make you feel "ohh, I didn't expect that to happen".
